"""Add visited models

Revision ID: 4e442a229f0a
Revises: 9df0a9af6e8b
Create Date: 2020-11-14 22:13:27.206913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e442a229f0a'
down_revision = '9df0a9af6e8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fruiting_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qualities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('yields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('properties', sa.Column('date_visited', sa.DateTime(), nullable=True))
    op.add_column('properties', sa.Column('fruiting_status_id', sa.Integer(), nullable=True))
    op.add_column('properties', sa.Column('quality_id', sa.Integer(), nullable=True))
    op.add_column('properties', sa.Column('yield_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'properties', 'qualities', ['quality_id'], ['id'])
    op.create_foreign_key(None, 'properties', 'yields', ['yield_id'], ['id'])
    op.create_foreign_key(None, 'properties', 'fruiting_statuses', ['fruiting_status_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'properties', type_='foreignkey')
    op.drop_constraint(None, 'properties', type_='foreignkey')
    op.drop_constraint(None, 'properties', type_='foreignkey')
    op.drop_column('properties', 'yield_id')
    op.drop_column('properties', 'quality_id')
    op.drop_column('properties', 'fruiting_status_id')
    op.drop_column('properties', 'date_visited')
    op.drop_table('yields')
    op.drop_table('qualities')
    op.drop_table('fruiting_statuses')
    # ### end Alembic commands ###
