"""added month fk

Revision ID: 9df0a9af6e8b
Revises: 
Create Date: 2020-11-10 13:37:17.131533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9df0a9af6e8b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('en_name', sa.String(length=200), nullable=True),
    sa.Column('en_synonyms', sa.String(length=200), nullable=True),
    sa.Column('en_wikipedia_url', sa.String(length=200), nullable=True),
    sa.Column('category_mask', sa.String(length=200), nullable=True),
    sa.Column('scientific_name', sa.String(length=200), nullable=True),
    sa.Column('scientific_synonyms', sa.String(length=300), nullable=True),
    sa.Column('taxonomic_rank', sa.String(length=100), nullable=True),
    sa.Column('pending', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_ids', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('unverified', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('import_link', sa.String(length=200), nullable=True),
    sa.Column('hidden', sa.Boolean(), nullable=True),
    sa.Column('no_season', sa.Boolean(), nullable=True),
    sa.Column('season_start_id', sa.Integer(), nullable=True),
    sa.Column('season_stop_id', sa.Integer(), nullable=True),
    sa.Column('access_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['access_id'], ['accesses.id'], ),
    sa.ForeignKeyConstraint(['season_start_id'], ['seasons.id'], ),
    sa.ForeignKeyConstraint(['season_stop_id'], ['seasons.id'], ),
    sa.ForeignKeyConstraint(['type_ids'], ['types.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('properties')
    op.drop_table('users')
    op.drop_table('types')
    op.drop_table('seasons')
    op.drop_table('accesses')
    # ### end Alembic commands ###
