"""removed address

Revision ID: ee44edd6876f
Revises: 2f0220386778
Create Date: 2020-11-06 18:07:34.359607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee44edd6876f'
down_revision = '2f0220386778'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
